name: phylon_analysis
channels:
  - defaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - plotly
  - jupyterlab
  - biopython
  - mkl
  - mkl-service
  - pip
  - cd-hit
  - reportlab
  - pip:
      - ete3==3.1.3
      - pygenomeviz==1.4.2
      - pyvis==0.3.2
      - svglib==1.4.1