name: phylon_analysis
channels:
  - plotly
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ansi2html=1.9.1
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - atk-1.0=2.36.0
  - attrs=23.2.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - biopython=1.84
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.7.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - cd-hit=4.8.1
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - dash=2.16.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrez-direct=21.6
  - executing=0.8.3
  - expat=2.5.0
  - flask=3.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gawk=5.1.0
  - gdk-pixbuf=2.42.10
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gobject-introspection=1.78.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.1.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipywidgets=8.1.2
  - itsdangerous=2.1.2
  - jedi=0.18.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jupyter-dash=0.4.2
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - kaleido-core=0.2.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libpng=1.6.39
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.13.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mafft=7.525
  - markupsafe=2.1.3
  - mathjax=2.7.7
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - matplotlib-venn=1.1.1
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.98
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.3.2
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - patsy=0.5.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.20.0
  - plotly_express=0.4.1
  - poppler=24.09.0
  - poppler-data=0.4.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycirclize=1.6.0
  - pycparser=2.21
  - pydot=3.0.1
  - pygments=2.15.1
  - pygraphviz=1.9
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-kaleido=0.2.1
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.34.0
  - requests=2.31.0
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - scikit-learn=1.4.1.post1
  - scipy=1.13.0
  - seaborn=0.12.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - threadpoolctl=3.4.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - upsetplot=0.9.0
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=3.0.2
  - wget=1.21.4
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - chardet==5.2.0
      - cssselect2==0.7.0
      - ete3==3.1.3
      - jsonpickle==3.2.2
      - lxml==5.3.0
      - pmw-py3==2.1
      - preppy==4.2.3
      - pygenomeviz==1.4.2
      - pypdf==5.1.0
      - pyvis==0.3.2
      - reportlab==4.2.5
      - rlextra==4.2.5.1
      - svglib==1.4.1
